window.__EN={
    "ey-f":"FAQ", "f-h":"What people ask<br>before ordering", "q1":"How much does a website cost?", "fa1":"Business-card site — 8 000 ₽, Tilda site — 10 000 ₽, WordPress — 12 000 ₽, corporate site — 20 000 ₽, online store — 25 000 ₽. These are the starting prices from the price list. The exact figure is agreed after a short brief, put in writing, and does not change unless the task changes.", "q2":"How much is a Telegram bot?", "fa2":"A Telegram bot is 8 000 ₽ per the price list, delivered in 1–2 days. That includes hooking it up to spreadsheets or a CRM and notifications about new requests.", "q3":"What are the timelines?", "fa3":"Business-card site or landing page — 2–4 days, corporate site — 5–8 days, online store — 10–14 days, Telegram bot — 1–2 days, presentation — 1–2 days.", "q4":"What is included in the price of a site?", "fa4":"Structure, design, responsive markup from 320 px, request forms, basic SEO setup (meta tags, sitemap, robots), domain and SSL setup, a walkthrough so you can edit the texts yourself, and 14 days of free revisions within the agreed scope.", "q5":"How much is a presentation?", "fa5":"From 5 000 ₽ per deck, or from 500 ₽ per slide. From 1 day, rush jobs accepted. You get an editable file — PowerPoint, Google Slides or Figma.", "q6":"Do you only work in Kazan?", "fa6":"No. We are based in Kazan but work remotely — across Russia and beyond. There is no office for visitors: everything is agreed over chat or a call, you do not need to travel anywhere.", "q7":"Do I pay separately for hosting and a domain?", "fa7":"Connecting the domain and issuing SSL are part of the work and are not billed separately. The domain itself is bought from a registrar in your name — for .ru that is usually 700–1100 ₽ a year, .com costs more. Hosting depends on the project: some sites run on free hosting, the rest usually cost 150–400 ₽ a month.", "q8":"How does payment work?", "fa8":"Usually a deposit up front and the rest after delivery and review. The exact arrangement is up to you — I will adapt. The price is fixed in writing before the work starts and does not change unless the task changes.",
    nav1:"Services", nav2:"Process", nav3:"Reviews", nav4:"Brief", nav5:"Work", nav6:"Pricing",
    mb1:"Send a request", "ey-a":"About", "a-h":"Websites, Telegram bots and presentations",
    "a-1":"YSD DEV is a studio based in Kazan, working remotely across Russia and abroad — no need to travel anywhere, everything is agreed over chat or a call.",
    "a-2":"We build websites end to end — business-card sites, landing pages, corporate sites and online stores on WordPress, Tilda or hand-coded. We develop Telegram bots for bookings, orders, payments and customer support, wired into CRM and spreadsheets. We turn Figma and PSD files into responsive HTML from 320px. And we design presentations and sales proposals.",
    "a-3":"A website price includes structure, design, responsive layout, lead forms, basic SEO, domain and SSL setup, plus training so you can edit texts yourself. The quote and deadline arrive on day one, progress is shown every 1–2 days, and 14 days of revisions after delivery are free.",
    "a-4":"Rated 4.87 on Profi.ru — 30 reviews are shown here. 35 projects in the portfolio. Scoping is free — describe what you need and get a price and a timeline.", aiT:"YSD DEV helper", aiS:"Instant answers · a human is one tap away", aiPh:"Ask anything about your order",
    "s-all":"Full price list, 36 services ↓",
    "ey-w":"Work", "w-h":"35 projects<br>in the portfolio",
    "w-l":"Websites, Telegram bots and decks. Tap a card to open it full size.",
    sl1:"Websites, end to end — from 8 000 ₽", sl2:"Online store — 25 000 ₽", sl3:"WordPress site — 12 000 ₽",
    sl4:"Telegram bot — 8 000 ₽", sl5:"Figma to HTML — from 3 000 ₽", sl6:"Presentation design — from 5 000 ₽",
    sl7:"Landing page — from 8 000 ₽", sl8:"Tilda website — 10 000 ₽", sl9:"Corporate website — 20 000 ₽", sl10:"Site fixes — from 2 000 ₽", sl11:"Company deck — from 5 000 ₽", sl12:"Investor pitch deck — from 8 000 ₽", sl13:"Video presentation — from 6 000 ₽", sl14:"Chatbot for business — 8 000 ₽", sl15:"What a website costs — price guide", sl16:"Beauty salon website — from 8 000 ₽", sl17:"Car service website — from 8 000 ₽", sl18:"Construction company website — from 12 000 ₽", sl19:"Booking bot — 8 000 ₽", sl20:"Tender presentation — from 5 000 ₽",
    "a-5":"We break down market prices — what these jobs actually cost at freelancers, studios and agencies, what drives the number and where cutting corners backfires.",
    ar1:"What a presentation costs", ar2:"What a landing page costs", ar3:"What an online store costs", ar4:"What a Tilda site costs", ar5:"What a business-card site costs", ar6:"What a Telegram bot costs", ar7:"Landing page vs website", ar8:"What a chatbot costs", ar9:"Tilda or WordPress", ar10:"What a domain and hosting cost", ar11:"What site maintenance costs", ar12:"What a turnkey site includes", ar13:"AI-built sites: what works", ar14:"AI-built decks: what works",
    fsv:"Services",
    ctc0:"Not a fan of forms —",
    "ey-p":"Pricing", "pr-h":"Prices known<br>before we talk",
    "pr-l":"No \u201cwe\u2019ll quote it individually\u201d. Three ready packages cover nine tasks out of ten \u2014 amounts and timelines below.",
    "pr-l2":"Need something separate — the full 36-service list is below. Starting prices; the exact number comes after a short brief.",
    "cm-h":"What people compare us to",
    cm1b:"Site builder", cm1p:"from 10,900 ₽",
    cm1s:"A ready template plus 490–800 ₽ a month. The site lives on their platform — stop paying and it goes dark.",
    cm2b:"Web studio", cm2p:"from 108,000 ₽",
    cm2s:"An account manager, a forty-question brief, 14–45 days. Good work — but it needs the budget and the time.",
    cm3b:"YSD DEV", cm3p:"8,000 – 30,000 ₽",
    cm3s:"Custom design, no subscription, domain and source files are yours. 2–14 days. I do it myself — you don’t pay for an office or account managers.",
    "cm-n":"Competitor prices taken from their public pages in September 2026.",
    pk1s:"Domain, hosting and SSL — set up at no extra charge",
    pk2s:"The same work bought line by line — <s>25,000 ₽</s>",
    pk3s:"The same work bought line by line — <s>35,000 ₽</s>",
    pk1h:"Page", pk1w:"One service or product. The visitor has to get it and write to you.",
    pk1t:"2–4 days", pk1a:"Up to 5 screens: offer, services, prices, reviews, form",
    pk1b:"Responsive on phone and tablet", pk1c:"Lead form with a Telegram notification to you",
    pk1d:"Domain, hosting and SSL set up by me", pk1e:"14 days of edits after handover",
    "pk-tag":"Most ordered", pk2h:"Website", pk2w:"Several services or directions. You want to be found in search.",
    pk2t:"5–8 days", pk2a:"Up to 6 pages, each aimed at its own query",
    pk2b:"Custom design, not a stock template", pk2c:"I help gather and write the copy",
    pk2d:"Online booking, calculator or quiz — your pick", pk2e:"Analytics with goals and SEO markup",
    pk2f:"30 days of edits after handover",
    pk3h:"Store", pk3w:"Selling on the site, or leads flowing into your CRM.",
    pk3t:"10–14 days", pk3a:"Catalogue, product cards, cart, checkout",
    pk3b:"Online payments and delivery cost calculation", pk3c:"Or a corporate site wired into your CRM",
    pk3d:"Admin panel and training — you take it from there", pk3e:"60 days of edits after handover",
    "pk-cta":"Discuss the task", "pk-cta2":"Discuss the task", "pk-cta3":"Discuss the task",
    g1b:"Mock-up before payment", g1s:"I show the home page design first. Not a fit — we part ways, you owe nothing.",
    g2b:"The price does not grow", g2s:"The sum is fixed in writing and does not move while the task does not.",
    g3b:"Everything is in your name", g3s:"Domain, hosting, source files and access — yours from day one.",
    g4b:"Staged payment", g4s:"Part after the mock-up is approved, the rest after handover.",
    pn1:"on the second service in one project", pn2:"scoping and the quote", pn3:"days of revisions after handover — depends on the package",
    status:"Taking new projects",
    h1a:"Websites, Telegram bots and decks —", h1b:"end to end.",
    sub:"You get a fixed quote and a firm deadline on day one, progress every 1–2 days, and 14 days of free revisions.",
    cta1:"Send a request", cta2:"Services & pricing",
    st0v:"4.87", st1:"Rating", st2:"Reviews", st2v:"30", st3:"Services", st4:"Lead time", st4v:"from 1 day",
    ey1:"Services", "s-h":"What we build",
    "s-l":"Fixed quotes, clear deadlines, everything handed over in editable form. Scoping is free.",
    sv1d:"Landing page in 2–4 days, corporate site in 5–8, store in 10–14. WordPress, Tilda or hand-coded. Structure, design, responsive layout, forms, basic SEO, domain and SSL, handover training.", sv1p:"from 12 000 ₽",
    sv2d:"Leads, payments, broadcasts, routine automation. Hooked up to spreadsheets and CRM, with an admin panel and owner notifications.", sv2p:"8 000 ₽",
    sv3d:"From a Figma or PSD file: HTML, CSS, JS, responsive from 320px, cross-browser, forms wired up. From 2 days.", sv3p:"from 3 000 ₽",
    sv4d:"Adapting an existing site to phones and tablets: menus, forms, tables, load speed. Tested on real iPhone and Android devices.", sv4p:"from 5 000 ₽",
    sv5d:"End to end: structure, design, infographics, one consistent style. PowerPoint, Google Slides or Figma — delivered editable. From 500 ₽ per slide.", sv5p:"from 5 000 ₽",
    sv6d:"Small fixes and consulting at an hourly rate. Full projects are quoted as a fixed price — it works out cheaper for you.", sv6p:"from 2 000 ₽/h",
    disc:"when you order two services together",
    ey2:"Process", "p-h":"Four steps,<br>no endless back and forth",
    p1d:"You message on Telegram. I ask 3–5 questions that matter — scoping is free.",
    p2d:"On day one you get the exact price, the scope and the deadline.",
    p3d:"Progress shown every 1–2 days. Always reachable, changes handled as we go.",
    p4d:"Domain, SSL, handover training. 14 days of free revisions after delivery.",
    ey3:"Reviews", "r-h":"4.87 out of 5 · 30 reviews", "r-l":"Reviews from my Profi.ru profile, rated 4.87 out of 5 there. 30 reviews here: the 12 main ones up front, the rest open with the button. Originals are behind the link below.",
    "r-src":"Source:",
    ey4:"Brief", "b-h":"Three clicks<br>and your brief is ready",
    "b-l":"Tick what you need. The page writes the message for you, copies it, and opens the chat — just paste and send.",
    "b-h":"Send a request",
    "b-l":"Three fields is all it takes. We answer around the clock, within 5 minutes, with an exact price and timeline.",
    f1:"Your name", f2:"Where to reply", f3:"What you need",
    ph0:"Name", ph1:"@telegram, phone or e-mail", ph2:"For example: a landing page for a car service, logo ready, needed within a week",
    
    agree:'I consent to the processing of my personal data under the <button type="button" class="lk" id="openLegal">data-processing policy</button>, including cross-border transfer to Telegram',
    terms:'By submitting the form you accept the <button type="button" class="lk" id="openLegal2">terms of use</button>.',
    send:"Send a request",
    hint:"Scoping and the quote are free. We answer around the clock, within 5 minutes.",
    okT:"Request sent", okD:"It is already in my Telegram. I will reply within 5 minutes with an exact quote and deadline.", lgT:"Terms of use and consent to data processing", lgOk:"I accept", lgDate:"Version of 11 September 2026",
    fcopy:"© 2026 YSD DEV · Kazan · working remotely worldwide",
    _greet:"New request from the YSD DEV site",
    _task:"Task", _name:"Name", _contact:"Contact", _from:"Page",
    _pick:"pick an option on the left",
    _sending:"Sending…",
    _copied:"Could not reach the bot — the text is copied and Telegram is opening. Paste it and send.",
    _manual:"Could not reach the bot. Telegram is opening — describe the task in a message."
  };
