window.__LEGAL=(function(TG){return {
    ru:
        '<p class="lg-rev">Редакция от 11 сентября 2026 года. Документ объединяет пользовательское соглашение, политику в отношении обработки персональных данных и текст согласия, которое вы даёте при отправке формы.</p>' +
        '<h4>1. Термины и стороны</h4>' +
        '<p>Сайт — интернет-ресурс по адресу ysddev.com со всеми его страницами. Пользователь — любой посетитель Сайта. Оператор (Владелец) — YSD DEV, e-mail theysddev@gmail.com, Telegram ' + '@' + TG + '.</p>' +
        '<p>Оператор работает как частное лицо и ведёт деятельность дистанционно; помещения для приёма посетителей нет. Полные реквизиты предоставляются по запросу через указанные контакты и в договоре.</p>' +
        '<p>Использование Сайта означает согласие с настоящим документом. Если вы с ним не согласны — не пользуйтесь Сайтом и не отправляйте форму.</p>' +
        '<h4>2. Статус сведений на Сайте</h4>' +
        '<p>Все материалы Сайта, включая цены, сроки и описания услуг, носят информационный характер и не являются публичной офертой по смыслу статьи 437 Гражданского кодекса РФ. Итоговая стоимость, состав работ и срок определяются отдельно после обсуждения задачи и фиксируются в переписке или договоре.</p>' +
        '<p>На странице приведены отзывы с профиля Оператора на сервисе Профи.ру; оригиналы доступны по ссылке на профиль. Изображения в разделе работ — демонстрационные проекты и концепты, выполненные для показа возможностей. Названия компаний, логотипы, цифры, фотографии и контакты на макетах вымышлены и не относятся к реальным организациям; товарные знаки третьих лиц, если они встречаются, принадлежат их правообладателям.</p>' +
        '<h4>3. Права на содержимое</h4>' +
        '<p>Тексты, оформление и программный код Сайта принадлежат Оператору. Товарные знаки, логотипы и наименования третьих лиц, встречающиеся в демонстрационных макетах, принадлежат их правообладателям и используются исключительно в оформительских целях. Копирование материалов в коммерческих целях без письменного разрешения не допускается. Ссылка на Сайт и цитирование с указанием источника разрешены.</p>' +
        '<h4>4. Ограничение ответственности</h4>' +
        '<p>Сайт предоставляется «как есть». Оператор не отвечает за перерывы в доступе, вызванные работой хостинга, домена, сети связи или действиями третьих лиц, а также за последствия использования информации с Сайта без предварительного согласования задачи.</p>' +
        '<h4>5. Персональные данные: оператор и правовое основание</h4>' +
        '<p>Оператором персональных данных является лицо, указанное в пункте 1. Обработка ведётся в соответствии с Федеральным законом от 27.07.2006 № 152-ФЗ «О персональных данных».</p>' +
        '<p>Правовое основание обработки — согласие субъекта персональных данных (пункт 1 части 1 статьи 6 Закона № 152-ФЗ), которое вы даёте, отмечая соответствующее поле в форме, а также исполнение договора, стороной которого вы становитесь, если работа согласована.</p>' +
        '<h4>6. Какие данные обрабатываются</h4>' +
        '<ul><li>контакт, который вы указали сами: ник в Telegram, номер телефона или адрес электронной почты;</li><li>имя или обращение, если вы его указали;</li><li>содержание вашего сообщения — описание задачи;</li><li>технические сведения, передаваемые браузером автоматически: адрес страницы, с которой отправлена заявка, дата и время обращения.</li></ul>' +
        '<p>Специальные категории персональных данных (статья 10 Закона № 152-ФЗ) и биометрические персональные данные (статья 11) не обрабатываются. Оператор не запрашивает паспортные данные, реквизиты банковских карт, пароли и иные чувствительные сведения — не указывайте их в поле сообщения.</p>' +
        '<h4>7. Цели обработки</h4>' +
        '<p>Связаться с вами по вашему обращению, уточнить задачу, подготовить смету и срок, выполнить и сдать работы, вести переписку по проекту. Данные не используются для рекламных рассылок без отдельного согласия, не продаются и не передаются в маркетинговых целях.</p>' +
        '<h4>8. Перечень действий и способы обработки</h4>' +
        '<p>Обрабатываются следующие действия: сбор, запись, систематизация, накопление, хранение, уточнение (обновление, изменение), извлечение, использование, передача (в объёме пункта 9), блокирование, удаление и уничтожение. Обработка ведётся смешанным способом — автоматизированно и без использования средств автоматизации. Решения, порождающие юридические последствия, исключительно на основании автоматизированной обработки не принимаются. Профилирование не применяется.</p>' +
        '<h4>9. Передача третьим лицам и трансграничная передача</h4>' +
        '<p>Заявка доставляется в Telegram-бот Оператора и проходит через сервис Telegram Messenger Inc. Сайт размещён на GitHub Pages (GitHub, Inc., США), домен обслуживается регистратором ООО «Таймвэб» (Россия). Доставка заявки выполняется через Google Apps Script (Google LLC, США). Шрифты загружаются с серверов Google Fonts (Google LLC, США).</p>' +
        '<p>Тем самым при отправке формы происходит трансграничная передача персональных данных на территорию иностранных государств. Отмечая поле согласия, вы соглашаетесь и на такую передачу (статья 12 Закона № 152-ФЗ). Иным третьим лицам данные не передаются, за исключением случаев, прямо предусмотренных законом.</p>' +
        '<h4>10. Сроки хранения и отзыв согласия</h4>' +
        '<p>Данные хранятся не дольше одного года с момента обращения либо до отзыва согласия — в зависимости от того, что наступит раньше. Если по обращению заключён договор, срок хранения продлевается на период его исполнения и на срок, установленный законом для хранения связанных документов.</p>' +
        '<p>Отозвать согласие можно в любой момент: сообщением в Telegram ' + '@' + TG + ' или письмом на theysddev@gmail.com. Из каналов Оператора данные удаляются в течение 10 рабочих дней с момента получения обращения, о чём вам сообщается тем же каналом. Сроки хранения на стороне сервисов из пункта 9 регулируются их собственными политиками.</p>' +
        '<h4>11. Меры защиты</h4>' +
        '<p>Сайт работает по протоколу HTTPS. Помимо Оператора, техническую возможность доступа к содержанию заявки имеют поставщики сервисов, перечисленные в пункте 9, на условиях их собственных политик. Токен доступа к Telegram-боту хранится на стороне сервера и на Сайте не публикуется. Оператор принимает правовые, организационные и технические меры, необходимые для защиты данных от неправомерного доступа, уничтожения, изменения и распространения.</p>' +
        '<h4>12. Cookie и подсчёт посещений</h4>' +
        '<p>Рекламных cookie и рекламного профилирования на Сайте нет. Для отображения шрифтов подключается сервис Google Fonts (Google LLC, США): при загрузке страницы ваш браузер обращается к серверам fonts.googleapis.com и fonts.gstatic.com и передаёт им IP-адрес и данные о браузере на условиях Google.</p><p>На Сайте работает система веб-аналитики Яндекс.Метрика (счётчик № 112490537), которую предоставляет ООО «ЯНДЕКС», Россия, 119021, Москва, ул. Льва Толстого, 16. Метрика сохраняет в вашем браузере собственные cookie и с их помощью собирает обезличенные сведения о посещении: IP-адрес, тип устройства и браузера, разрешение экрана, регион по IP, источник перехода, просмотренные страницы, время на них, клики и прокрутку. Дополнительно включён Вебвизор — он записывает движения курсора, прокрутку и нажатия, чтобы можно было увидеть, на каком месте страницы посетители теряются. Содержимое полей формы Вебвизор не записывает: значения полей скрываются на стороне счётчика, в записи видно только сам факт заполнения.</p><p>Эти данные обрабатываются на условиях Яндекса и используются исключительно для оценки посещаемости и удобства Сайта, а не для рекламы. Условия: yandex.ru/legal/confidential. Отказаться от сбора можно в любой момент: расширением «Блокировщик Яндекс.Метрики» (yandex.ru/support/metrica/general/opt-out.html), режимом инкогнито, блокировкой сторонних cookie или любым блокировщиком трекеров — на работу Сайта и на отправку заявки это никак не влияет.</p>' +
        '<h4>13. Ваши права</h4>' +
        '<p>Вы вправе получить сведения об обработке своих персональных данных, требовать их уточнения, блокирования или уничтожения, отозвать согласие, а также обжаловать действия Оператора в Роскомнадзоре или в суде. Обращение направляется по контактам из пункта 1; ответ предоставляется в срок, установленный статьёй 20 Закона № 152-ФЗ.</p>' +
        '<h4>14. Несовершеннолетние</h4>' +
        '<p>Сайт не предназначен для лиц младше 18 лет и не собирает их данные осознанно. Если вы младше 18 лет, отправляйте заявку только с согласия родителя или иного законного представителя.</p>' +
        '<h4>15. Согласие, которое вы даёте</h4>' +
        '<p>Отмечая поле в форме и отправляя заявку, вы подтверждаете, что ознакомились с настоящим документом, и даёте Оператору согласие на обработку указанных вами персональных данных в перечисленных целях, перечисленными способами, включая трансграничную передачу, на срок из пункта 10, с правом отзыва в любой момент.</p>' +
        '<h4>16. Изменения</h4>' +
        '<p>Оператор вправе изменять настоящий документ. Действующая редакция всегда доступна на этой странице; дата редакции указана в начале. Существенные изменения не имеют обратной силы для уже поданных заявок.</p>',

    en:
        '<p class="lg-rev">Version of 11 September 2026. This document combines the terms of use, the personal-data processing policy and the text of the consent you give when submitting the form.</p>' +
        '<h4>1. Definitions and parties</h4>' +
        '<p>The Site — the web resource at ysddev.com and all of its pages. User — any visitor. Operator (Owner) — YSD DEV, e-mail theysddev@gmail.com, Telegram ' + '@' + TG + '.</p>' +
        '<p>The Operator works as a private individual and operates remotely; there is no office for visitors. Full legal details are provided on request through the contacts above and in the contract.</p>' +
        '<p>Using the Site means you accept this document. If you do not accept it, please do not use the Site and do not submit the form.</p>' +
        '<h4>2. Status of the information on the Site</h4>' +
        '<p>All materials, including prices, timelines and service descriptions, are informational and do not constitute a public offer under Article 437 of the Civil Code of the Russian Federation. The final price, scope and deadline are agreed separately and recorded in correspondence or a contract.</p>' +
        '<p>The page shows the reviews from the Operator’s Profi.ru profile; the originals are available at the profile link. Images in the work section are demonstration projects and concepts made to show capability. Company names, logos, figures, photographs and contacts inside the mock-ups are invented and refer to no real organisation; any third-party trademarks belong to their owners.</p>' +
        '<h4>3. Rights to the content</h4>' +
        '<p>Texts, design and code of the Site belong to the Operator. Third-party trademarks, logos and names appearing in the demonstration mock-ups belong to their respective owners and are used for illustrative purposes only. Commercial copying without written permission is not allowed. Linking and quoting with attribution are permitted.</p>' +
        '<h4>4. Limitation of liability</h4>' +
        '<p>The Site is provided “as is”. The Operator is not liable for interruptions caused by hosting, domain, network or third-party actions, nor for consequences of relying on the Site’s information without agreeing the task first.</p>' +
        '<h4>5. Personal data: operator and legal basis</h4>' +
        '<p>The data controller is the person named in clause 1. Processing is carried out under Russian Federal Law No. 152-FZ of 27 July 2006 “On Personal Data”.</p>' +
        '<p>The legal basis is the data subject’s consent (Art. 6(1)(1) of Law 152-FZ), given by ticking the box in the form, and — where work is agreed — performance of the contract to which you become a party.</p>' +
        '<h4>6. What data is processed</h4>' +
        '<ul><li>the single contact you provide: Telegram handle, phone number or e-mail;</li><li>your name or preferred form of address, if provided;</li><li>the content of your message — the task description;</li><li>technical data sent by the browser automatically: the page the request was sent from, date and time.</li></ul>' +
        '<p>Special categories of personal data (Art. 10) and biometric personal data (Art. 11) are not processed. The Operator never asks for ID documents, card details or passwords — please do not put them in the message field.</p>' +
        '<h4>7. Purposes</h4>' +
        '<p>To contact you about your request, clarify the task, prepare an estimate and timeline, carry out and deliver the work, and correspond about the project. Data is not used for marketing mailings without separate consent, is not sold and is not shared for marketing.</p>' +
        '<h4>8. Actions and methods of processing</h4>' +
        '<p>The following actions are performed: collection, recording, systematisation, accumulation, storage, updating, retrieval, use, transfer (within clause 9), blocking, deletion and destruction. Processing is mixed — automated and non-automated. No decisions producing legal effects are made solely by automated processing. No profiling is applied.</p>' +
        '<h4>9. Third parties and cross-border transfer</h4>' +
        '<p>Requests are delivered to the Operator’s Telegram bot and therefore pass through Telegram Messenger Inc. The Site is hosted on GitHub Pages (GitHub, Inc., USA); the domain is served by Timeweb LLC (Russia). Delivery runs through Google Apps Script (Google LLC, USA). Fonts are loaded from Google Fonts (Google LLC, USA).</p>' +
        '<p>Submitting the form therefore involves a cross-border transfer of personal data. By ticking the consent box you also consent to such transfer (Art. 12 of Law 152-FZ). No data is shared with any other third party except where required by law.</p>' +
        '<h4>10. Retention and withdrawal of consent</h4>' +
        '<p>Data is kept for no longer than one year from the request, or until consent is withdrawn — whichever comes first. If a contract results, retention extends for its performance and for any period required by law for related documents.</p>' +
        '<p>You may withdraw consent at any time by messaging Telegram ' + '@' + TG + ' or writing to theysddev@gmail.com. Data is deleted from the Operator’s own channels within 10 working days and you are notified through the same channel. Retention on the side of the services listed in clause 9 is governed by their own policies.</p>' +
        '<h4>11. Security measures</h4>' +
        '<p>The Site runs over HTTPS. Besides the Operator, the service providers listed in clause 9 technically have access to the contents of a request, under their own policies. The Telegram bot token is stored server-side and never published on the Site. The Operator applies the legal, organisational and technical measures needed to protect data from unlawful access, destruction, alteration and disclosure.</p>' +
        '<h4>12. Cookies and visit counting</h4>' +
        '<p>There are no advertising cookies and no advertising profiling on the Site. Google Fonts (Google LLC, USA) is used for typography: loading the page makes your browser contact fonts.googleapis.com and fonts.gstatic.com, passing them your IP address and browser data on Google’s terms.</p><p>The Site runs Yandex.Metrica web analytics (counter no. 112490537), provided by YANDEX LLC, 16 Lva Tolstogo St., Moscow 119021, Russia. Metrica stores its own cookies in your browser and collects anonymised visit data: IP address, device and browser type, screen resolution, region by IP, referrer, pages viewed, time on them, clicks and scrolling. Session Replay (Webvisor) is also enabled: it records cursor movement, scrolling and clicks so that it is possible to see where visitors get stuck. Form field contents are not recorded — field values are masked on the counter side, and a replay only shows that a field was filled in.</p><p>This data is processed on Yandex’s terms and is used solely to measure traffic and usability, not for advertising. Terms: yandex.ru/legal/confidential. You can opt out at any time using the Yandex.Metrica opt-out add-on (yandex.ru/support/metrica/general/opt-out.html), private browsing, third-party cookie blocking or any tracker blocker — none of this affects the Site or the request form.</p>' +
        '<h4>13. Your rights</h4>' +
        '<p>You may obtain information about the processing of your data, require its correction, blocking or destruction, withdraw consent, and complain to Roskomnadzor or a court. Requests go to the contacts in clause 1 and are answered within the period set by Art. 20 of Law 152-FZ.</p>' +
        '<h4>14. Minors</h4>' +
        '<p>The Site is not intended for persons under 18 and does not knowingly collect their data. If you are under 18, submit the form only with the consent of a parent or legal guardian.</p>' +
        '<h4>15. The consent you give</h4>' +
        '<p>By ticking the box and submitting the form you confirm that you have read this document and give the Operator your consent to process the personal data you provide, for the purposes and by the methods listed, including cross-border transfer, for the period in clause 10, with the right to withdraw at any time.</p>' +
        '<h4>16. Changes</h4>' +
        '<p>The Operator may amend this document. The current version is always available on this page and dated at the top. Material changes do not apply retroactively to requests already submitted.</p>'
  };})("ysddev");
